# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-30 17:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Id', models.CharField(max_length=10)),
                ('Faculty_Name', models.CharField(max_length=50)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('ENC', 'E and C'), ('ISE', 'ISE')], default='CSE', max_length=10)),
                ('Designation', models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Prof.', 'Professor'), ('HOD', 'HOD'), ('Asst.Prof.', 'Asst.Professor'), ('Asst.Prof.', 'Asst.Professor')], max_length=20)),
                ('Experience', models.IntegerField(blank=True, help_text='Number of years', max_length=2)),
                ('Achievements', models.CharField(blank=True, max_length=250)),
                ('Message', models.CharField(blank=True, help_text='Message to students', max_length=250)),
                ('Contact', models.CharField(blank=True, max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=50)),
                ('Photo', models.ImageField(blank=True, upload_to='images/')),
                ('Created_Date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=50)),
                ('Specialization', models.CharField(blank=True, max_length=200)),
                ('Sub_notes', models.FileField(blank=True, upload_to='documents/')),
                ('sub_Video', models.FileField(blank=True, upload_to='videos/')),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReqDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Req_Type', models.CharField(max_length=25)),
                ('Req_details', models.CharField(blank=True, max_length=250)),
                ('sender_id', models.CharField(blank=True, max_length=10)),
                ('receiver_id', models.CharField(blank=True, max_length=10)),
                ('Req_Status', models.CharField(blank=True, default='Pending', max_length=20)),
                ('dateof_request', models.DateField(default=datetime.date.today)),
                ('dateof_update', models.DateField(blank=True, default=datetime.date.today)),
                ('reply_details', models.CharField(blank=True, max_length=250)),
                ('visibilty_sender_id', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('visible_to_Hod', models.BooleanField(default=False)),
                ('visible_to_Principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReqTypes',
            fields=[
                ('Req_Type_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Req_Type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Id', models.CharField(max_length=12)),
                ('Student_Name', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('ENC', 'E and C'), ('ISE', 'ISE')], max_length=10)),
                ('Semester', models.PositiveIntegerField(blank=True, max_length=1)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=10)),
                ('Contact', models.CharField(blank=True, max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=30)),
            ],
        ),
    ]
