# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Experience',
            field=models.IntegerField(blank=True, help_text='Number of years'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Semester',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
