# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200819_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Place',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
